Feat: Re-factor python-install role
- Add new version 3.10.x support.
- Bump 3.8.x to most recent releanse
- Bump 3.9.x to most recent releanse
- Bump the pyenv version to v2.3.3.
- Remove old deprecated version of python:
  (3.4.10, 3.5.10, 3.6.13)
- Refactor the python-install role to address 'line too
   long' error while building the pyenv command.
- Install compact-openssl10 dependencies for python 3.10
  ERROR: The Python ssl extension was not compiled. Missing the
  OpenSSL lib?
  The compat-openssl libs are available only for CentOS8, so python
  3.10x will be available for >= CentOS8.
- Include libssl-dev required for building Ubuntu {18,20}.04

Issue-ID: RELENG-4357
Ref: https://github.com/pyenv/pyenv/issues/950
Change-Id: I3fe4fed872a43bf21a07fefc6c161b143f306ca2
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>